#!/bin/bash
set -eux

root=$(dirname $0)
source $root/secrets
source $root/openrc

db_pass=stackdb

function install_svc {
  local name=$1
  local remote=$2
  local branch=${3:-master}

  if grep "^sudo:" /etc/group; then
    id $name || useradd -G sudo -m $name -s /bin/false
  fi
  if grep "^admin:" /etc/group; then
    id $name || useradd -G admin -m $name -s /bin/false
  fi

  mkdir -p /opt/stack
  for d in /var/log/$name /var/run/$name /etc/$name; do
    mkdir -p $d
    chown -R $name $d
  done

  if [ ! -e /opt/stack/$name ]; then
  #if ! yolk -V $name; then
    #git clone --depth 1 -b master $remote $temp/$name
    git clone -b $branch $remote /opt/stack/$name
    pip install /opt/stack/$name
  fi
}

function create_db {
  local sql="
    drop database if exists $1; -- TODO: remove this
    create database if not exists $1;
    grant all on $1.* to '$2'@'*'         identified by '$3';
    grant all on $1.* to '$2'@'localhost' identified by '$3';
    grant all on $1.* to '$2'@'%'         identified by '$3';
    flush privileges;"
  mysql -uroot -p$db_pass -e "$sql"
}

function install_upstart {
  local name=$1
  local user=$2
  local cmd=$3
  shift; shift; shift
  local args=$*
  cat > /etc/init/$name.conf <<EOF
start on runlevel [2345]
stop on runlevel [016]
chdir /var/run/$user
setuid $user
respawn
exec start-stop-daemon --start --make-pidfile --pidfile /var/run/$user/$name.pid --exec $cmd -- $args >> /var/log/$user/$name.log 2>&1
EOF
}

function ensure_root {
  if (( EUID != 0 )); then
    echo "You must be root to do this." 1>&2
    exit 1
  fi
}

function give_sudo {
  grep $1 /etc/sudoers || echo "$1 ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
}

function install-packages {
  DEBIAN_FRONTEND=noninteractive apt-get install -y $*
}

function install_deps {
  # apt-get update
  echo mysql-server-5.1 mysql-server/root_password password $db_pass | debconf-set-selections
  echo mysql-server-5.1 mysql-server/root_password_again password $db_pass | debconf-set-selections
  install-packages git ipmitool mysql-server python-dev python-novaclient python-pip python-numpy python-lxml python-greenlet python-mysqldb ccze libxml2-dev libxslt-dev python-zmq
  install-packages openvswitch-common openvswitch-controller openvswitch-switch
  os-config-applier --help || pip install -e git+https://github.com/tripleo/os-config-applier.git#egg=os-config-applier
  #yolk || pip install yolk
}

################################

function keystone_install {
  install_svc keystone https://github.com/openstack/keystone.git
  install_upstart keystone keystone /usr/local/bin/keystone-all "--config-dir /etc/keystone --log-config /etc/keystone/logging.conf"
  mkdir -p /etc/keystone/ssl && chown -R keystone:keystone /etc/keystone/ssl
  create_db keystone keystone $db_pass
}

function keystone_first_start {
  keystone-manage db_sync
  keystone-manage pki_setup
  service keystone restart
}

################################

function glance_install {
  install_svc glance https://github.com/openstack/glance.git
  mkdir -p /var/lib/glance/images && chown -R glance:glance /var/lib/glance/images
  install_upstart glance-api glance /usr/local/bin/glance-api "--debug --log-config /etc/glance/logging.conf"
  install_upstart glance-reg glance /usr/local/bin/glance-registry "--debug --log-config /etc/glance/logging.conf"
  create_db glance glance $db_pass
}

function glance_first_start {
  glance-manage db_sync
  service glance-reg restart
  service glance-api restart
}

################################

function cinder_install {
  install-packages lvm2
  install_svc cinder https://github.com/openstack/cinder.git
  give_sudo cinder
  install_upstart cinder-api cinder /usr/local/bin/cinder-api ""
  install_upstart cinder-volume cinder /usr/local/bin/cinder-volume ""
  install_upstart cinder-scheduler cinder /usr/local/bin/cinder-scheduler ""
  create_db cinder cinder $db_pass
}

function cinder_first_start {
  cinder-manage db sync
  service cinder-api restart
  service cinder-volume restart
  service cinder-scheduler restart
}

################################

function horizon_install {
  install-packages nodejs python-openssl python-dev
  which node || ln -s $(which nodejs) /usr/bin/node
  install_svc horizon https://github.com/openstack/horizon.git
  if [ ! -e /opt/stack/horizon/.venv ]; then python /opt/stack/horizon/tools/install_venv.py; fi
  mkdir -p /opt/stack/horizon/static && chown -R horizon:horizon /opt/stack/horizon/static
  install_upstart horizon horizon /opt/stack/horizon/manage.py "runserver 0.0.0.0:8080"
}

function horizon_first_start {
  service horizon restart
}

################################

function nova_install {
  install-packages rabbitmq-server
  sudo rabbitmqctl change_password guest stackqueue
  install_svc nova https://github.com/tripleo/nova.git baremetal-dev
  give_sudo nova
  mkdir -p /var/run/nova/keys && chown -R nova /var/run/nova/keys
  install_upstart nova-api              nova /usr/local/bin/nova-api   "--config-dir /etc/nova"
  install_upstart nova-rpc-zmq-receiver nova /usr/local/bin/nova-rpc-zmq-receiver "--config-dir /etc/nova"
  install_upstart nova-compute          nova /usr/local/bin/nova-compute "--config-dir /etc/nova"
  install_upstart nova-cert             nova /usr/local/bin/nova-cert   "--config-dir /etc/nova"
  install_upstart nova-scheduler        nova /usr/local/bin/nova-scheduler "--config-dir /etc/nova --debug"
  install_upstart nova-consoleauth      nova /usr/local/bin/nova-consoleauth   "--config-dir /etc/nova"
  install_upstart nova-conductor        nova /usr/local/bin/nova-conductor "--config-dir /etc/nova"
  install_upstart nova-baremetal-deploy-helper nova /usr/local/bin/nova-baremetal-deploy-helper "--config-dir /etc/nova"
  create_db nova nova $db_pass
  create_db nova_bm nova $db_pass

  # TODO: XXX XXX XXX
  # stop all dnsmasqs
  # run nova-compute as root so it can use its dnsmasq helper.
  # - failed ipmi ssh - host key not accepted?

  mkdir -p /tftpboot/pxelinux.cfg/

  install-packages dnsmasq
  # TODO: config options:
  cat > /etc/init/nova-dnsmasq.conf <<eof
start on runlevel [2345]
stop on runlevel [016]
chdir /var/run/nova
setuid root
respawn
exec start-stop-daemon --start --make-pidfile --pidfile /var/run/nova/nova-dnsmasq.pid --exec /usr/sbin/dnsmasq -- --conf-file= --port=0 --enable-tftp --tftp-root=/tftpboot         --dhcp-boot=pxelinux.0 --bind-interfaces --pid-file=/var/run/dnsmasq.pid         --interface=em3 --dhcp-range='192.0.2.65,192.0.2.69,29' >> /var/log/nova/nova-dnsmasq.log 2>&1
eof
  service stop dnsmasq || echo "dnsmasq not running"
  rm -f /etc/init.d/dnsmasq || ech "no dnsmasq init.d script"
  chown -R nova:nova /var/lib/misc/
}

function nova_first_start {
  service nova-dnsmasq restart
  nova-manage db sync
  nova-baremetal-manage db sync

  service nova-api restart
  sleep 5
  service nova-cert restart
  service nova-rpc-zmq-receiver restart
  service nova-compute restart
  service nova-scheduler restart
  service nova-consoleauth restart
  service nova-conductor restart
  service nova-baremetal-deploy-helper restart
}

################################

function quantum_install {
  install_svc quantum https://github.com/openstack/quantum.git
  give_sudo quantum
  mkdir -p /var/lib/quantum && chown -R quantum:quantum /var/lib/quantum
  install_upstart quantum-server quantum /usr/local/bin/quantum-server "--config-dir /etc/quantum"
  install_upstart quantum-openvswitch-agent quantum /usr/local/bin/quantum-server "--config-dir /etc/quantum --debug"
  install_upstart quantum quantum /usr/local/bin/quantum "--config-dir /etc/quantum --debug"
  
  create_db ovs_quantum quantum $db_pass
}

function quantum_first_start {
  service quantum-server restart
  service quantum-openvswitch-agent restart
  service quantum restart
}

################################

function install_all {
  rm -rf /var/log/quantum /var/log/nova /var/log/glance /var/log/cinder /var/log/keystone || echo "ok"
  install_deps
  keystone_install
  nova_install
  quantum_install
  glance_install
  horizon_install
  cinder_install
}

function start_all {
  keystone_first_start
  nova_first_start
  quantum_first_start
  cinder_first_start
  glance_first_start
  horizon_first_start
  sleep 10
  $root/keystone_setup

}

function add_bm_node {
  id=$(nova-baremetal-manage node create --host $1 --cpus $2 --memory_mb $3 --local_gb $4 --pm_address $5 --pm_user $6 --pm_pass $7 --terminal_port 0 --prov_mac $8)
  nova-baremetal-manage interface create --node_id $id --mac_address $8 --datapath_id 0 --port_no 0
}

function test_all {
  echo '' | nc localhost 5000 || die "keystone not running"

  if [ ! -e $root/cirros.qcow2 ]; then
    curl -L -o $root/cirros.qcow2 "https://launchpad.net/cirros/trunk/0.3.0/+download/cirros-0.3.0-x86_64-disk.img"
  fi


  source $root/adminrc
  glance image-create --name cirros --is-public true --container-format bare --disk-format qcow2 < cirros.qcow2


  # TODO: hostnames
  # TODO: config
  add_bm_node bm-aw1az2-freecloud0007.freecloud.hpcloud.net 1 4096 20 $IPMI_IP $IPMI_USER $IPMI_PASS $IPMI_MAC


  PHYSICAL_NETWORK=em3
  TENANT_ID=admin
  ALLOCATION_POOL="start=192.0.2.34,end=192.0.2.38"
  NETWORK_GATEWAY=10.10.16.129
  FIXED_RANGE=192.0.2.32/29
  OVS_PHYSICAL_BRIDGE=br-ctlplane
  OVS_VLAN_RANGES=$PHYSICAL_NETWORK
  Q_PLUGIN_CONF_FILE=/etc/quantum/quantum.conf
  PUBLIC_INTERFACE=em3
  #iniset /$Q_PLUGIN_CONF_FILE OVS network_vlan_ranges $OVS_VLAN_RANGES
#  nova-manage network create --label private --fixed_range_v4 '192.0.2.32/8' --num_networks 1 --network_size 10 --bridge_interface em3
  ovs-vsctl --no-wait -- --may-exist add-br br-ctlplane
  ovs-vsctl --no-wait -- --may-exist add-port br-ctlplane bm3
  for IP in $(ip addr show dev $PUBLIC_INTERFACE | grep ' inet ' | awk '{print $2}'); do
    sudo ip addr del $IP dev $PUBLIC_INTERFACE
    sudo ip addr add $IP dev $OVS_PHYSICAL_BRIDGE
  done
  NET_ID=$(quantum net-create $PHYSICAL_NETWORK --tenant_id $TENANT_ID --provider:network_type flat --provider:physical_network "$PHYSICAL_NETWORK" | grep ' id ' | awk '{print $2}')
  echo "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  echo $NET_ID
  SUBNET_ID=$(quantum subnet-create --tenant_id $TENANT_ID --ip_version 4 --allocation-pool "$ALLOCATION_POOL" --gateway $NETWORK_GATEWAY $NET_ID $FIXED_RANGE | grep ' id ' | awk '{print $2}')
  sudo ifconfig $OVS_PHYSICAL_BRIDGE up

  /home/tim/git/incubator/scripts/loadimage ami test /home/tim/test.qcow2
  local kernel=$(nova image-list | grep aki | head -1 | awk '{print $2}')
  local ramdisk=$(nova image-list | grep ari | head -1 | awk '{print $2}')

  nova flavor-create x86_bm    100 512 20 1
    nova flavor-key x86_bm set \
            cpu_arch=x86 \
            deploy_kernel_id=$kernel \
            deploy_ramdisk_id=$ramdisk

  nova flavor-create x86_64_bm 101 512 20 1
    nova flavor-key x86_64_bm set \
            cpu_arch=x86_64 \
            deploy_kernel_id=$kernel \
            deploy_ramdisk_id=$ramdisk

}

function main {
  ensure_root
  install_all
  os-config-applier --templates $root/templates --metadata $root/init-data.json
  start_all
  test_all
  echo ok
}

main
